---
# tasks file for ansible-role-locale

- name: Configure locale definitions.
  template:
    src: locale.gen.j2
    dest: /etc/locale.gen
  notify: generate locale

- name: Configure system locale.
  template:
    src: locale.conf.j2
    dest: /etc/locale.conf
